# Auto-generated by Terraform
# Run: ansible-playbook -i inventory.ini playbook.yml

[servers]
${public_ip} ansible_user=ubuntu ansible_ssh_private_key_file=${ssh_key_path}

[servers:vars]
ansible_python_interpreter=/usr/bin/python3
