---
# Auto-generated by Terraform
# Copy this file to all.yml and fill in the placeholders:
#   cp group_vars/all.yml.example group_vars/all.yml

app_name: culrecords
app_dir: "/home/ubuntu/{{ app_name }}"

# Domain and SSL (optional)
domain_name: ""  # e.g. "records.example.com"
use_ssl: false

# Database configuration
db_user: calebrecords
db_password: "CHANGE_ME_OR_USE_TERRAFORM_VALUE"
db_name: calebrecords

# Backend secret
secret_key: "CHANGE_ME_OR_USE_TERRAFORM_VALUE"

# CORS origins - update with your production domains
cors_origins: "http://localhost:5173,http://localhost:5174,https://tauri.localhost,http://${public_ip},http://${public_ip}/staff"

# SMTP configuration (optional)
smtp_host: ""
smtp_port: 587
smtp_user: ""
smtp_password: ""
smtp_from: "noreply@calebuniversity.edu.ng"

# S3 backup bucket (auto-generated by Terraform)
s3_backup_bucket: "${s3_bucket}"

# RDS endpoint (only used if create_rds = true in Terraform)
rds_endpoint: "${rds_endpoint}"

# Git repository to clone
git_repo: "https://github.com/YOUR_USERNAME/caleb-records.git"
git_branch: "main"
